# Generated by Django 5.0.14 on 2025-10-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Categoria')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine di visualizzazione')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Prodotto')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('specifiche_tecniche', models.TextField(blank=True, verbose_name='Specifiche Tecniche')),
                ('prezzo_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Base (€)')),
                ('disponibile', models.BooleanField(default=True, verbose_name='Disponibile')),
                ('in_evidenza', models.BooleanField(default=False, verbose_name='In Evidenza')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='prodotti.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Prodotto',
                'verbose_name_plural': 'Prodotti',
                'ordering': ['-in_evidenza', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ImmagineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_immagine', models.ImageField(upload_to='prodotti/%Y/%m/', verbose_name='Immagine')),
                ('alt_text', models.CharField(help_text="Descrizione dell'immagine per SEO e accessibilità", max_length=200, verbose_name='Testo alternativo')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('is_principale', models.BooleanField(default=False, verbose_name='Immagine Principale')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='prodotti.prodotto', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Immagine Prodotto',
                'verbose_name_plural': 'Immagini Prodotto',
                'ordering': ['-is_principale', 'ordine'],
            },
        ),
    ]
