# Generated by Django 5.0.14 on 2025-10-04 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        ('prodotti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_preventivo', models.CharField(max_length=20, unique=True, verbose_name='Numero Preventivo')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('stato', models.CharField(choices=[('BOZZA', 'Bozza'), ('INVIATO', 'Inviato'), ('ACCETTATO', 'Accettato'), ('RIFIUTATO', 'Rifiutato')], default='BOZZA', max_length=20, verbose_name='Stato')),
                ('totale_stimato', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Totale Stimato (€)')),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sconto (%)')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('validita_giorni', models.IntegerField(default=30, verbose_name='Validità (giorni)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventivi', to='clienti.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Preventivo',
                'verbose_name_plural': 'Preventivi',
                'ordering': ['-data_creazione'],
            },
        ),
        migrations.CreateModel(
            name='VocePreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantità')),
                ('prezzo_unitario_finale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo Unitario (€)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('preventivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voci', to='preventivi.preventivo', verbose_name='Preventivo')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prodotti.prodotto', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Voce Preventivo',
                'verbose_name_plural': 'Voci Preventivo',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
