# Generated by Django 5.0.14 on 2025-10-04 12:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cognome', models.CharField(max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('data_registrazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Appuntamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(verbose_name='Data e Ora')),
                ('tipo_consulenza', models.CharField(choices=[('CONSULENZA', 'Consulenza Progettuale'), ('RILIEVO', 'Rilievo Misure'), ('PREVENTIVO', 'Discussione Preventivo'), ('ALTRO', 'Altro')], default='CONSULENZA', max_length=20, verbose_name='Tipo Consulenza')),
                ('stato', models.CharField(choices=[('RICHIESTO', 'Richiesto'), ('CONFERMATO', 'Confermato'), ('COMPLETATO', 'Completato'), ('ANNULLATO', 'Annullato')], default='RICHIESTO', max_length=20, verbose_name='Stato')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appuntamenti', to='clienti.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Appuntamento',
                'verbose_name_plural': 'Appuntamenti',
                'ordering': ['-data_ora'],
            },
        ),
    ]
